// services/reelService.js
// Thin wrapper – reels are primarily generated by aiService.
// This service handles batching & pre-fetching for smooth reel navigation.

const { generateReel } = require("./aiService");
const NodeCache = require("node-cache");

const reelCache = new NodeCache({ stdTTL: 600 });

async function getReelForArticle(article) {
  const hit = reelCache.get(article.id);
  if (hit) return hit;

  const reel = await generateReel(article);
  reelCache.set(article.id, reel);
  return reel;
}

// Pre-fetch reels for a list of articles (called after feed loads)
async function prefetchReels(articles = []) {
  const todo = articles.filter(a => !reelCache.has(a.id)).slice(0, 5);
  await Promise.allSettled(todo.map(a => getReelForArticle(a)));
}

module.exports = { getReelForArticle, prefetchReels };
